# Generated by Django 4.2.1 on 2023-07-23 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                ("descricao", models.TextField()),
                (
                    "data",
                    models.DateField(
                        default=datetime.datetime(2023, 7, 23, 12, 4, 56, 143349)
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("E", "Entrada"), ("S", "Saída")], max_length=1
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perfil.banco"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfil.categoria",
                    ),
                ),
            ],
        ),
    ]
