# Generated by Django 4.2.1 on 2023-07-24 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
        ("bancos", "0001_initial"),
        ("extrato", "0028_alter_valores_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valores",
            name="banco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bancos.banco"
            ),
        ),
        migrations.AlterField(
            model_name="valores",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categorias.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="valores",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 24, 0, 38, 4, 626987)
            ),
        ),
        migrations.AlterField(
            model_name="valores", name="tipo", field=models.CharField(max_length=1),
        ),
    ]
