# Generated by Django 4.2.1 on 2023-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apelido", models.CharField(max_length=50)),
                (
                    "banco",
                    models.CharField(
                        choices=[
                            ("NU", "Nubank"),
                            ("XP", "XP"),
                            ("CR", "Clear"),
                            ("IT", "Itau"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pf", "Pessoa Física"), ("pj", "Pessoa Jurídica")],
                        max_length=2,
                    ),
                ),
                ("saldo", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("essencial", models.BooleanField(default=False)),
                ("valor_planejamento", models.FloatField(default=0)),
            ],
        ),
    ]
