# Generated by Django 4.2.1 on 2023-07-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extrato", "0029_alter_valores_banco_alter_valores_categoria_and_more"),
        ("contas", "0002_alter_contapagar_categoria"),
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Banco",),
        migrations.DeleteModel(name="Categoria",),
    ]
