# Generated by Django 4.2.1 on 2023-07-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=30)),
                ("apelido", models.CharField(max_length=30)),
                ("tipo", models.CharField(max_length=2)),
                ("saldo", models.FloatField()),
            ],
        ),
    ]
