# Generated by Django 4.2.1 on 2023-07-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contapagar",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="categorias.categoria",
            ),
        ),
    ]
